### ISSUE TITLE
How to record and playback macros

### ISSUE THREAD

**Issue by bacon-5665** [dkhachatrian/xinput-pybot#1]
I came across this which is exactly what I needed but I can't figure out how recording and playing back macros works. I got the test controller working and the values change when I press buttons but I can't figure out how to start recording. I assume I enter the value I got from test controller as the reader and the refresh rate of how many inputs per second but that's as much as I can figure out. 
Sorry I know you haven't really done anything with this project in a year but it would be awesome if you could give me some instructions on recording and playing back macros.

**Comment by dkhachatrian** [comment]
Let's see how much of this I remember haha.

From what you've said, it sounds like you've set up the "tubes" as listed in the readme? (Homebrew `pyvjoy`, `pyxinput`, `pywin32`, etc.)

From what I remember (and looking through the docstrings in `macro_handler`, the flow would be something like

```
import macro_handler as mh
import pyxinput

# record gamepad input in slot slot_num -- this will be one macro
reader = pyxinput.rController(slot_num)
macro_dict = mh.record_gamepad_reader(reader) # records until KeyboardInterrupt

# playback macro:
# first get handle to VJoy device
j = pyvjoy.VJoyDevice(1) # gives handle to VJoyDevice with ID = 1

# now run macro -- starts immediately
# if window focus is important for the VJoy inputs to be read properly,
# that still needs to be handled
mh.run_macro(j, macro_dict)
```

(We omit the `converter` argument from `record_gamepad_reader` to use a default function to convert the pyxinput states into a set of VJoy states (which should work as long as your VJoy device has enough buttons and axes to properly mimic an XInput device).)

If your VJoyDevice needs to be read as an XInput device, you'll need to set up the VJoy device in XOutput. I have a sample config file for XOutput as the `vjoy_device_config_for_xoutput.txt` file in the `example_configs` folder.

Hopefully this helps!

**Comment by bacon-5665** [comment]
Hey, I gave it a go but when I try to define macro_dict it starts the recorder but after I KeyboardInterrupt it throws this error 
```
File "C:\Users\Billy\Desktop\xinput-pybot-master\record.py", line 5, in <module>
    macro_dict = mh.record_gamepad_reader(reader, 60)
  File "C:\Users\Billy\Desktop\xinput-pybot-master\macro_handler.py", line 253, in record_gamepad_reader
    states = converter(states)
  File "C:\Users\Billy\Desktop\xinput-pybot-master\macro_handler.py", line 197, in xinput_macro_to_vjoy_macro
    unconverted_buttons = state.pop('wButtons')
AttributeError: '_xinput_gamepad' object has no attribute 'pop'
```
my vJoy device has 16 buttons and all Axes checked and my controller works when I test it. 
This is what I'm running.
```
import macro_handler as mh
import pyxinput

reader = pyxinput.rController(1)
macro_dict = mh.record_gamepad_reader(reader, 60)
```

**Comment by dkhachatrian** [comment]
Ah, I could have sworn I had fixed that before -- thanks for bringing it up!

Fixed it on my end. I'll make a pull request on a `bugfix` branch and reference this issue. Check out the new branch and if everything runs fine on your end too, let me know and I'll merge the branch (and close this issue).

**Comment by dkhachatrian** [comment]
Will merge bugfix and close this issue for now (since it seems to be fixed on my end with the patch). If there's another issue when using, feel free to open a new issue!
